name: Reusable Deploy
# 아티팩트의 key와 같은 외부 입력값을 받기 위하여 nested 형식으로 변경합니다.
# on: workflow_call
on:
  workflow_call:
    # 재사용 워크플로우에서 필요한 값을 입력받기 위해 inputs를 지정합니다.
    inputs: 
      # 필요한 데이터를 받기 위한 키를 원하는대로 지정합니다.
      artifact-name: 
        # 지정한 input 키가 어떤 데이터를 입력받아야 하는 지를 설명합니다.
        description: The name of the deployable artifact files
        # 해당 input이 필수인지를 나타냅니다.
        required: false
        # required가 필수가 아닐 때, 기본 값을 설정합니다.
        default: dist
        # input의 타입을 지정합니다. (string | number | boolean)
        type: string
jobs:
  deploy: 
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/download-artifact@v3
        with:
          # 다른 워크플로우에서 지정한 key를 곧바로 재사용 워크플로우에서 사용할 수는 없습니다.
          # name: dist-files
          #
          # inputs 컨텍스트로부터 지정한 input 값을 가져와서 사용합니다.
          name: ${{ inputs.artifact-name }}
      - name: List files
        run: ls
      - name: Output information
        run: echo "Deploying & uploading..."